backend:
  name: git-gateway
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Author
        name: author
        widget: string
        default: Nathan Graule
        required: false
      - label: Publish date
        name: date
        widget: datetime
        format: YYYY-MM-DD
      - label: Tags
        name: tags
        widget: list
      - label: Part of series
        name: series
        widget: object
        required: false
        fields:
          - label: Part number
            name: part
            widget: number
            valueType: int
            min: 1
            step: 1
          - label: Previous part
            name: prev
            required: false
            default: null
            type: relation
            collection: pages
            valueField: "{{slug}}"
            searchFields:
              - title
              - subtitle
              - tags
              - body
            displayFields: "{{title}} by {{author}}"
          - label: Next part
            name: next
            required: false
            default: null
            type: relation
            collection: pages
            valueField: "{{slug}}"
            searchFields:
              - title
              - subtitle
              - tags
              - body
            displayFields: "{{title}} by {{author}}"
      - label: Content
        name: body
        widget: markdown
